project:
  output-dir: ./docs/en

website:
  title: "Swisstransplant Data Science"
  site-url: "https://data.swisstransplant.org/"
  description: "Statistical reporting and research at Swisstransplant."
  search: false
  favicon: images/SWT_icon_kreis_blau_2020_196x196.png
  navbar:
    logo: "images/SWT_2955_2021.png"
    title: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Statistical Reports"
        href: posts.qmd
      - text: "Research"
        menu:
        - tools/index.qmd
        - text: "KIDMO"
          href: kidmo/index.qmd
        - text: "EXAM"
          href: https://swisstransplant.shinyapps.io/EXAM/
          icon: "box-arrow-up-right"
          target: _blank
        - text: "Publications"
          href: publications/index.qmd
      - text: "About"
        href: about/index.qmd
    right:
      - text: "DE"
        href: ..
      - text: "FR"
        href: ../fr
        
  page-footer:
    left: '© 2023--2025 Swisstransplant'

lang: en

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    link-external-icon: true
    link-external-newwindow: true
