project:
  type: website
  output-dir: docs

website:
  title: "Data Science"
  site-url: "https://swtdata.org/"
  description: "Tools and software developed at Swisstransplant."
  search: false
  navbar:
    logo: "images/swt.png"
    left:
      - text: Home
        href: index.qmd
      - text: Research Tools
        href: tools/index.qmd
      - text: KIDMO
        href: kidmo/index.qmd
      - text: EXAM
        href: https://swisstransplant.shinyapps.io/EXAM/
      - text: About
        href: about/index.qmd
      - icon: github
        href: https://github.com/Swisstransplant
  page-footer:
    left: '© 2023 Swisstransplant'

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
