project:
  type: website
  output-dir: ./docs

website:
  title: "Swisstransplant Data"
  site-url: "https://data.swisstransplant.org/"
  description: "Online-Plattform mit aktuellen Statistiken und Analysetools im Bereich Organspende und Transplantation."
  search: false
  open-graph: true
  favicon: images/SWT_icon_kreis_blau_2020_196x196.png
  navbar:
    title: false
    logo: "images/SWT_2955_2021.png"
    logo-alt: "Swisstransplant logo"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Statistiken"
        href: posts.qmd
      - text: "Forschung"
        menu:
        - tools/index.qmd
        - text: "KIDMO"
          href: kidmo/index.qmd
        - text: "EXAM"
          href: exam/index.qmd
        - text: "Publikationen"
          href: publications/index.qmd
      - text: "Über uns"
        href: about/index.qmd
    right:
      - text: "FR"
        href: ./fr
        
  page-footer:
    left: '© 2023--2025 Swisstransplant'
  google-analytics:
    tracking-id: "G-NJH1JBVDQV"
    anonymize-ip: true

lang: de

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    link-external-icon: true
    link-external-newwindow: true
