project:
  output-dir: ./docs

website:
  title: "Swisstransplant Data Science"
  site-url: "https://data.swisstransplant.org/"
  description: "Statistisches Reporting und Forschung bei Swisstransplant."
  search: false
  favicon: images/SWT_icon_kreis_blau_2020_196x196.png
  navbar:
    logo: "images/SWT_2955_2021.png"
    title: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Statistiken"
        href: posts.qmd
      - text: "Forschung"
        menu:
        - tools/index.qmd
        - text: "KIDMO"
          href: kidmo/index.qmd
        - text: "EXAM"
          href: https://swisstransplant.shinyapps.io/EXAM/
          icon: "box-arrow-up-right"
          target: _blank
        - text: "Publikationen"
          href: publications/index.qmd
      - text: "Über uns"
        href: about/index.qmd
    right:
      - text: "FR"
        href: ./fr
#      - text: "EN"
#        href: ./en
        
  page-footer:
    left: '© 2023, 2024 Swisstransplant'

lang: de

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
