project:
  type: website
  output-dir: docs

website:
  title: "Data Science"
  search: false
  navbar:
    logo: "swt.png"
    left:
      - text: Home
        href: index.qmd
      - text: Research Tools
        href: tools.qmd
      - text: KIDMO
        href: https://swisstransplant.shinyapps.io/KIDMO/
      - text: EXAM
        href: https://swisstransplant.shinyapps.io/EXAM/
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/Swisstransplant
  page-footer:
    left: '© 2023 Swisstransplant'

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true

editor: visual

