---
title: ""
---

<style>

.icon-color { 
  color: #F2AF5C;
}

.center-text { 
  text-align: center;
}

</style>

# Swisstransplant Data

::: {.content-visible when-profile="de"}
Swisstransplant Data stellt aktuelle Daten, Statistiken und interaktive Analyse-Tools zur Verfügung und unterstützt so die Forschung und Qualitätssicherung im Bereich Organspende und Transplantation.

::: {.center-text}
::: {.grid}

::: {.g-col-12 .g-col-md-4} 
::: {.icon-color}
{{< fa lightbulb size=2x >}}
:::
<span style="color:#2A548A;font-weight:bold;">Informieren</span>
<p>Wir publizieren transparente und aktuelle Kennzahlen zur Organspende und Transplantation.</p>
:::

::: {.g-col-12 .g-col-md-4} 
::: {.icon-color}
{{< fa user-doctor size=2x >}}
:::
<span style="color:#2A548A;font-weight:bold;">Befähigen</span>
<p>Wir unterstützen medizinisches Fachpersonal und Forschende mit Daten und massgefertigten Analyse-Tools.</p>
:::

::: {.g-col-12 .g-col-md-4} 
::: {.icon-color}
{{< fa rocket size=2x >}}
:::
<span style="color:#2A548A;font-weight:bold;">Verbessern</span>
<p>Wir publizieren Fachartikel und stärken gemeinsam Qualität und Evidenz in der Transplantationsmedizin.</p>
:::

:::
:::

Um mehr über Swisstransplant zu erfahren, besuchen Sie bitte unsere Webseite [www.swisstransplant.org](https://www.swisstransplant.org/de){target="_blank"}.
:::

::: {.content-visible when-profile="fr"}
Swisstransplant Data met à disposition des données actuelles, des statistiques et des outils d'analyse interactifs, soutenant ainsi la recherche et l'assurance qualité dans le domaine du don d'organes et de la transplantation.

::: {.center-text}
::: {.grid}

::: {.g-col-12 .g-col-md-4} 
::: {.icon-color}
{{< fa lightbulb size=2x >}}
:::
<span style="color:#2A548A;font-weight:bold;">Informer</span>
<p>Nous publions des chiffres clés transparents et actualisés sur le don d'organes et la transplantation.</p>
:::

::: {.g-col-12 .g-col-md-4} 
::: {.icon-color}
{{< fa user-doctor size=2x >}}
:::
<span style="color:#2A548A;font-weight:bold;">Habiliter</span>
<p>Nous aidons les professionnels de santé et les chercheurs en leur fournissant des données et des outils d'analyse sur mesure.</p>
:::

::: {.g-col-12 .g-col-md-4} 
::: {.icon-color}
{{< fa rocket size=2x >}}
:::
<span style="color:#2A548A;font-weight:bold;">Améliorer</span>
<p>Nous publions des articles spécialisés et renforçons ensemble la qualité et les preuves scientifiques dans le domaine de la médecine de transplantation.</p>
:::

:::
:::

Pour en savoir plus sur Swisstransplant, veuillez consulter notre site web [www.swisstransplant.org](https://www.swisstransplant.org/fr).
:::
