---
title: 'Multilanguage Postprocessing'
subtitle: 'Translating document tiles of a Quarto Website for improved multilingual support'
author: Simon Schwab
date: last-modified
abstract: 'Quarto websites only partly support multiple languages, for example, document titles and descriptions in the yaml header have no multilingual support. This document is a workaound and will translate document titles by reading the html files, translating the tiltes, and overwriten the html file.'
lang: en
format:
  html:
    toc: true
    theme: swt.scss
    df-print: kable
    embed-resources: true
    code-fold: true
---

::: {.callout-note}
This script needs to be applied after rendering the <https://data.swisstransplant.org> website. For a step-by-step instruction, see README at <https://github.com/Swisstransplant/swtdata>.
:::

## Home

The landing page does not need translation as the header Swisstransplant Data is multilingual.

## About page

### French

```{r}
file = "../docs/fr/about/index.html"
page = readLines(file, warn = FALSE)

page = gsub(x = page,
            pattern = "<title>Über uns – Swisstransplant Data</title>",
            replace = "<title>Qui sommes-nous? – Swisstransplant Data</title>")
page = gsub(x = page,
            pattern = "<h1 class=\"title\">Über uns</h1>", 
            replace = "<h1 class=\"title\">Qui sommes-nous?</h1>")

writeLines(page, con=file)
```

## Publications page

### French

```{r}
file = "../docs/fr/publications/index.html"
page = readLines(file, warn = FALSE)

page = gsub(x = page,
            pattern = "<title>Publikationen – Swisstransplant Data</title>",
            replace = "<title>Publications – Swisstransplant Data</title>")
page = gsub(x = page,
            pattern = "<h1 class=\"title\">Publikationen</h1>", 
            replace = "<h1 class=\"title\">Publications</h1>")

writeLines(page, con=file)
```

## Listing page for posts

### French

```{r}
file = "../docs/fr/posts.html"
page = readLines(file, warn = FALSE)

page = gsub(x = page,
            pattern = "<title>Statistiken – Swisstransplant Data</title>",
            replace = "<title>Rapports statistiques – Swisstransplant Data</title>")
page = gsub(x = page,
            pattern = "<h1 class=\"title\">Statistiken</h1>", 
            replace = "<h1 class=\"title\">Rapports statistiques</h1>")

page = gsub(x = page,
            pattern = "1. Quartal 2024", 
            replace = "1er trimestre 2024")

page = gsub(x = page,
            pattern = "2. Quartal 2024", 
            replace = "2e trimestre 2024")

page = gsub(x = page,
            pattern = "3. Quartal 2024", 
            replace = "3e trimestre 2024")

page = gsub(x = page,
            pattern = "4. Quartal 2024", 
            replace = "4e trimestre 2024")

page = gsub(x = page,
            pattern = "1. Quartal 2025", 
            replace = "1er trimestre 2025")

page = gsub(x = page,
            pattern = "2. Quartal 2025", 
            replace = "2e trimestre 2025")

page = gsub(x = page,
            pattern = "3. Quartal 2025", 
            replace = "3e trimestre 2025")

page = gsub(x = page,
            pattern = "4. Quartal 2025", 
            replace = "4e trimestre 2025")

page = gsub(x = page,
            pattern = "Jahreszahlen 2024", 
            replace = "Chiffres annuels 2024")

page = gsub(x = page,
            pattern = "Jahreszahlen 2025", 
            replace = "Chiffres annuels 2025")

page = gsub(x = page,
            pattern = "Wie lange wartet man auf ein Spendeorgan\\?", 
            replace = "Combien de temps faut-il attendre pour recevoir un organe ?")

writeLines(page, con=file)
```

## Posts

### French

```{r}
file = "../docs/fr/posts/2024-Q1/index.html"
page = readLines(file, warn = FALSE)

page = gsub(x = page,
            pattern = "<title>1. Quartal 2024 – Swisstransplant Data</title>", 
            replace = "<title>1er trimestre 2024 – Swisstransplant Data</title>")
page = gsub(x = page,
            pattern = "<h1 class=\"title\">1. Quartal 2024</h1>", 
            replace = "<h1 class=\"title\">1er trimestre 2024</h1>")

writeLines(page, con=file)
```

```{r}
file = "../docs/fr/posts/2024-Q2/index.html"
page = readLines(file, warn = FALSE)

page = gsub(x = page,
            pattern = "<title>2. Quartal 2024 – Swisstransplant Data</title>", 
            replace = "<title>2e trimestre 2024 – Swisstransplant Data</title>")
page = gsub(x = page,
            pattern = "<h1 class=\"title\">2. Quartal 2024</h1>", 
            replace = "<h1 class=\"title\">2e trimestre 2024</h1>")

writeLines(page, con=file)
```

```{r}
file = "../docs/fr/posts/2024-Q3/index.html"
page = readLines(file, warn = FALSE)

page = gsub(x = page,
            pattern = "<title>3. Quartal 2024 – Swisstransplant Data</title>", 
            replace = "<title>3e trimestre 2024 – Swisstransplant Data</title>")
page = gsub(x = page,
            pattern = "<h1 class=\"title\">3. Quartal 2024</h1>", 
            replace = "<h1 class=\"title\">3e trimestre 2024</h1>")

writeLines(page, con=file)
```

```{r}
file = "../docs/fr/posts/2024-Q4/index.html"
page = readLines(file, warn = FALSE)

page = gsub(x = page,
            pattern = "<title>4. Quartal 2024 – Swisstransplant Data</title>", 
            replace = "<title>4e trimestre 2024 – Swisstransplant Data</title>")
page = gsub(x = page,
            pattern = "<h1 class=\"title\">4. Quartal 2024</h1>", 
            replace = "<h1 class=\"title\">4e trimestre 2024</h1>")

writeLines(page, con=file)
```

```{r}
file = "../docs/fr/posts/2025-Q1/index.html"
page = readLines(file, warn = FALSE)

page = gsub(x = page,
            pattern = "<title>1. Quartal 2025 – Swisstransplant Data</title>", 
            replace = "<title>1er trimestre 2025 – Swisstransplant Data</title>")
page = gsub(x = page,
            pattern = "<h1 class=\"title\">1. Quartal 2025</h1>", 
            replace = "<h1 class=\"title\">1er trimestre 2025</h1>")

writeLines(page, con=file)
```

```{r}
file = "../docs/fr/posts/2025-Q2/index.html"
page = readLines(file, warn = FALSE)

page = gsub(x = page,
            pattern = "<title>2. Quartal 2025 – Swisstransplant Data</title>", 
            replace = "<title>2e trimestre 2025 – Swisstransplant Data</title>")
page = gsub(x = page,
            pattern = "<h1 class=\"title\">2. Quartal 2025</h1>", 
            replace = "<h1 class=\"title\">2e trimestre 2025</h1>")

writeLines(page, con=file)
```

```{r}
file = "../docs/fr/posts/2025-Q3/index.html"
page = readLines(file, warn = FALSE)

page = gsub(x = page,
            pattern = "<title>3. Quartal 2025 – Swisstransplant Data</title>", 
            replace = "<title>3e trimestre 2025 – Swisstransplant Data</title>")
page = gsub(x = page,
            pattern = "<h1 class=\"title\">3. Quartal 2025</h1>", 
            replace = "<h1 class=\"title\">3e trimestre 2025</h1>")

writeLines(page, con=file)
```

```{r}
file = "../docs/fr/posts/2025-Q4/index.html"
page = readLines(file, warn = FALSE)

page = gsub(x = page,
            pattern = "<title>4. Quartal 2025 – Swisstransplant Data</title>", 
            replace = "<title>4e trimestre 2025 – Swisstransplant Data</title>")
page = gsub(x = page,
            pattern = "<h1 class=\"title\">4. Quartal 2025</h1>", 
            replace = "<h1 class=\"title\">4e trimestre 2025</h1>")

writeLines(page, con=file)
```

```{r}
file = "../docs/fr/posts/2024/index.html"
page = readLines(file, warn = FALSE)

page = gsub(x = page,
            pattern = "<title>Jahreszahlen 2024 – Swisstransplant Data</title>", 
            replace = "<title>Chiffres annuels 2024 – Swisstransplant Data</title>")
page = gsub(x = page,
            pattern = "<h1 class=\"title\">Jahreszahlen 2024</h1>", 
            replace = "<h1 class=\"title\">Chiffres annuels 2024</h1>")

writeLines(page, con=file)
```

```{r}
file = "../docs/fr/posts/2025/index.html"
page = readLines(file, warn = FALSE)

page = gsub(x = page,
            pattern = "<title>Jahreszahlen 2025 – Swisstransplant Data</title>", 
            replace = "<title>Chiffres annuels 2025 – Swisstransplant Data</title>")
page = gsub(x = page,
            pattern = "<h1 class=\"title\">Jahreszahlen 2025</h1>", 
            replace = "<h1 class=\"title\">Chiffres annuels 2025</h1>")

writeLines(page, con=file)
```

```{r}
file = "../docs/fr/posts/2025-WL/index.html"
page = readLines(file, warn = FALSE)

page = gsub(x = page,
            pattern = "<title>Wie lange wartet man auf ein Spendeorgan\\? – Swisstransplant Data</title>", 
            replace = "<title>Combien de temps faut-il attendre pour recevoir un organe ? – Swisstransplant Data</title>")
page = gsub(x = page,
            pattern = "<h1 class=\"title\">Wie lange wartet man auf ein Spendeorgan\\?</h1>", 
            replace = "<h1 class=\"title\">Combien de temps faut-il attendre pour recevoir un organe ?</h1>")

writeLines(page, con=file)
```
